---
version: '3.2'

services:
    jenkins-master:
        image: sizgiyaev/spring-boot-example:0.0.1
        networks:
            - traefik-net
        deploy:
            mode: replicated
            replicas: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.role == worker
            labels:
                - "traefik.port=8080"
                - "traefik.docker.network=traefik-net"
                - "traefik.frontend.rule=Host:spring-boot-example.sizghome.net" 

networks:
    traefik-net:
        external: true